### ISSUE TITLE
Profile images

### ISSUE THREAD

**Issue by uzluisf** [salomonelli/best-resume-ever#2]
Hey Sara, 
I've given it a touch to the profile image and added two new ones. I still have the SVG files if you want to change the colors or do something similar.
![profile](https://user-images.githubusercontent.com/22332927/30243411-7ed851f8-9576-11e7-9c92-8afbbda638a2.png)

**Comment by salomonelli** [comment]
Hello @uzluisf 

thank you very much for your help. I really do like these two:
![image](https://user-images.githubusercontent.com/12084165/30248847-bce829be-962f-11e7-88f0-bb43494a9781.png)

Would it be possible to make the tie instead of checked, completely colored? Then it would be more neutral. A PR would be really great!

**Comment by uzluisf** [comment]
That sounds great, @salomonelli!
One thing I noticed is that with the original image, the actual resolution (719x719) doesn't seem to be the most optimal and this is more noticeable with templates (e.g. material-blue) that seems to enlarge the image.  Do you want to use a higher resolution?  Or just keep it as before?

**Comment by salomonelli** [comment]
No you can enlarge them of course. That would be great!
